import { Deck, DeckSchema, DeckSchemaVersion } from "@pagestate/ir";
import { TemplateInput } from "./template-schema.js";
import { createSlidesFromTemplates } from "./templates.js";

export const TEMPLATE_DEMO_INPUTS: TemplateInput[] = [
  {
    template: "hero",
    id: "hero_template",
    eyebrow: "PageState template system",
    title: "Reusable Slide Templates",
    subtitle: "Generate validated Slide IR from small structured inputs.",
    speakerNotes: "This opening page is generated by the hero template."
  },
  {
    template: "section",
    id: "section_template",
    sectionNumber: "01",
    title: "From Empty Slide to Intent",
    subtitle: "Templates give AI and users a higher-level way to create slides."
  },
  {
    template: "two-column",
    id: "two_column_template",
    title: "Two-Column Layout",
    left: {
      heading: "Input",
      items: ["Small schema", "Clear content roles", "Optional ordering"]
    },
    right: {
      heading: "Output",
      items: ["Validated Slide IR", "Stable block ids", "Renderable HTML"]
    }
  },
  {
    template: "comparison",
    id: "comparison_template",
    title: "Comparison Template",
    items: [
      {
        label: "Hand-written JSON",
        points: ["Flexible but verbose", "Easy to forget required fields", "Harder for AI to keep consistent"]
      },
      {
        label: "Template-generated IR",
        points: ["Shorter input", "Consistent structure", "Still validated by SlideSchema"]
      }
    ]
  },
  {
    template: "timeline",
    id: "timeline_template",
    title: "MVP Build Timeline",
    events: [
      {
        label: "Step 1",
        description: "Define Deck IR and validation."
      },
      {
        label: "Step 2",
        description: "Execute command-based mutations."
      },
      {
        label: "Step 3",
        description: "Render Deck IR to reveal.js."
      },
      {
        label: "Step 4",
        description: "Generate slides from reusable templates."
      }
    ]
  },
  {
    template: "chart-slide",
    id: "chart_template",
    title: "Template Coverage",
    chartTitle: "Template demo pages",
    chartType: "bar",
    columns: ["Template", "MVP value"],
    rows: [
      ["Hero", 5],
      ["Comparison", 5],
      ["Timeline", 4],
      ["Chart", 4],
      ["Closing", 3]
    ],
    insight: "The first template set covers opening, narrative, structure, data, and closing pages."
  },
  {
    template: "quote-hero",
    id: "quote_hero_template",
    quote: "Templates turn raw slide JSON into reusable presentation intent.",
    attribution: "PageState design note"
  },
  {
    template: "architecture",
    id: "architecture_template",
    title: "Template Pipeline",
    summary: "Templates sit above Deck IR and below AI or user intent.",
    steps: ["Template input", "Zod validation", "Slide IR generation", "Deck validation", "Reveal rendering"]
  },
  {
    template: "product-demo",
    id: "product_demo_template",
    title: "Product Demo Flow",
    summary: "A user can choose a template, fill a few fields, and receive a complete slide.",
    steps: ["Pick a template", "Fill structured fields", "Generate Slide IR", "Render a preview"]
  },
  {
    template: "closing",
    id: "closing_template",
    title: "Templates Are Ready",
    subtitle: "The next step can connect these templates to commands, AI generation, or a workbench UI.",
    nextSteps: ["Add richer visual styling", "Expose template commands", "Let AI choose templates"],
    contact: "github.com/zzz-k-k/PageState"
  }
];

export function createTemplateDemoDeck(): Deck {
  const deck = {
    schemaVersion: DeckSchemaVersion,
    type: "deck",
    id: "template_demo",
    title: "PageState Template Demo",
    description: "A generated deck that demonstrates the first PageState slide templates.",
    theme: {
      id: "template_demo_theme",
      name: "Template Demo",
      tokens: {
        colors: {
          "color.background": "#f8fafc",
          "color.surface": "#ffffff",
          "color.text.primary": "#111827",
          "color.text.muted": "#4b5563",
          "color.accent": "#0f766e"
        },
        fonts: {
          "font.heading": "Inter",
          "font.body": "Inter"
        },
        spacing: {
          "space.slide.x": 96,
          "space.slide.y": 72,
          "space.block.gap": 24
        },
        radii: {
          "radius.card": 8
        }
      }
    },
    slides: createSlidesFromTemplates(TEMPLATE_DEMO_INPUTS),
    exportConfig: {
      aspectRatio: "16:9",
      width: 1920,
      height: 1080,
      formats: ["html", "pdf", "png"]
    },
    metadata: {
      locale: "en-US",
      author: "PageState",
      tags: ["templates", "demo", "deck-ir"],
      createdAt: "2026-06-13T00:00:00.000Z",
      updatedAt: "2026-06-13T00:00:00.000Z"
    }
  };

  return DeckSchema.parse(deck);
}
